// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqWxdUE2r9pyzcDV7JgJzFcBGln8rHNM',
    appId: '1:785926613709:web:7ea532066a1c5422265784',
    messagingSenderId: '785926613709',
    projectId: 'messenger-9ca0c',
    authDomain: 'messenger-9ca0c.firebaseapp.com',
    storageBucket: 'messenger-9ca0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bPu9oM0402RF8vwbZQwpFzfXL980VHk',
    appId: '1:785926613709:android:b7295bbc96f9ebd2265784',
    messagingSenderId: '785926613709',
    projectId: 'messenger-9ca0c',
    storageBucket: 'messenger-9ca0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbuROge6gdNuMip7lu6F8NejA73h8Lss',
    appId: '1:785926613709:ios:27101e6fb3017de7265784',
    messagingSenderId: '785926613709',
    projectId: 'messenger-9ca0c',
    storageBucket: 'messenger-9ca0c.appspot.com',
    iosClientId: '785926613709-ktf4l367tfqf05ir46as89du3uu940co.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbuROge6gdNuMip7lu6F8NejA73h8Lss',
    appId: '1:785926613709:ios:38c40882c14b3e7f265784',
    messagingSenderId: '785926613709',
    projectId: 'messenger-9ca0c',
    storageBucket: 'messenger-9ca0c.appspot.com',
    iosClientId: '785926613709-q6lvs63u254auvm694lks053q4vfot67.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
